export enum UserRole {
  ADMIN = 'ADMIN',
  USER = 'USER',
}

export interface User {
  id: string;
  username: string;
  email: string;
  password_hash: string;
  role: UserRole;
  created_at: string; // ISO date string
  updated_at: string; // ISO date string
}

// Data transfer object for creating a user (omits fields generated by DB or service)
export type CreateUserDto = Pick<User, 'username' | 'email'> & {
  password: string; // Plain password, will be hashed by service
  role?: UserRole; // Optional, defaults to USER
};

// Data transfer object for updating user role
export type UpdateUserRoleDto = {
  role: UserRole;
};

// Data transfer object for public user representation (omits sensitive info)
export type PublicUserDto = Omit<User, 'password_hash'>; 